### ISSUE TITLE
markdownlint fails with error in CI

### ISSUE THREAD

**Issue by devth** [jpignata/codeclimate-markdownlint#21]
My markdownlint codeclimate engine is failing with:

```
/usr/local/bundle/gems/mdl-0.4.0/lib/mdl/doc.rb:57:in `read': No such file or directory @ rb_sysopen - README.md (Errno::ENOENT)
	from /usr/local/bundle/gems/mdl-0.4.0/lib/mdl/doc.rb:57:in `new_from_file'
	from /usr/local/bundle/gems/mdl-0.4.0/lib/mdl.rb:74:in `block in run'
	from /usr/local/bundle/gems/mdl-0.4.0/lib/mdl.rb:72:in `each'
	from /usr/local/bundle/gems/mdl-0.4.0/lib/mdl.rb:72:in `run'
	from /usr/local/bundle/gems/mdl-0.4.0/bin/mdl:10:in `<top (required)>'
	from /usr/local/bundle/bin/mdl:16:in `load'
	from /usr/local/bundle/bin/mdl:16:in `<main>'
```

Any idea what this means? It works when I run locally but not in CI.

Some debug output before the error:

```
[DEBUG] markdownlint:stable engine config: {"enabled":true,"include_paths":[".gitlab-ci.yml","README.md","eng/","CULTURE.md","PLANNING.md",".codeclimate.yml","COMMUNICATION.md"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-markdownlint-stable-70f10c9a-eeed-46e6-a2a6-c85cbe6f58af", "--cap-drop", "all", "--label", "com.codeclimate.label=0e94e854-176b-4b02-85c6-6b5732ee09ea", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/code:/code:ro", "--volume", "/tmp/cc/9ff5d1fc-1441-441f-8f7e-3181845cd097:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-markdownlint"]
```

btw, that volume syntax `"/code:/code:ro"` doesn't look right with 2 `:` in it.

**Comment by dblandin** [comment]
Hey @devth,

How are you invoking Code Climate in CI? I'm surprised by that volume argument.

The `:ro` bit is expected. That means that the engine container is only granted read access to the mounted volume.

I would expect a local system path to be mounted to `/code` within the container though.

For example, a local run on my machine has the following output:

```
[DEBUG] fixme:stable engine config: {"enabled":true,"include_paths":[".codeclimate.yml","README.md","codeclimate_test_reporter.egg-info/","codeclimate_test_reporter/",".gitignore","Makefile","Dockerfile","bin/","LICENSE.txt","setup.py","requirements.txt",".pypirc.sample","circle.yml","tox.ini","setup.cfg",".dockerignore"]}
[DEBUG] docker run: ["docker", "run", "--name", "cc-engines-fixme-stable-d76c0399-fa98-4604-8d3f-fa55200ee430", "--cap-drop", "all", "--label", "com.codeclimate.label=b1d7cfa1-a784-4499-864f-981fc27839f0", "--memory", "512000000", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/home/devon/code/codeclimate/python-test-reporter:/code:ro", "--volume", "/tmp/cc/8579acc2-cde7-485d-8c20-526e26d4b84e:/config.json:ro", "--user", "9000:9000", "codeclimate/codeclimate-fixme"]
```

with the following volume mount argument:

```
/home/devon/code/codeclimate/python-test-reporter:/code:ro
```

**Comment by devth** [comment]
Currently:

```
    docker run
      --rm
      --env CODECLIMATE_DEBUG=true
      --env CODE_PATH=/code
      --volume "$CI_PROJECT_DIR":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      --entrypoint sh
      codeclimate/codeclimate
      -c 'ls -al /code && /usr/src/app/bin/codeclimate analyze'
```

But I've tried without overriding the `entrypoint` too.

**Comment by devth** [comment]
Simplified to:

```
    docker run
      --rm
      --env CODECLIMATE_DEBUG=true
      --env CODE_PATH=/code
      --volume "$CI_PROJECT_DIR":/code
      --volume /var/run/docker.sock:/var/run/docker.sock
      --volume /tmp/cc:/tmp/cc
      codeclimate/codeclimate
```

Output:

```
Status: Downloaded newer image for codeclimate/codeclimate:latest
error: (NoMethodError) undefined method `any?' for nil:NilClass
[DEBUG] backtrace: /usr/src/app/lib/cc/cli/help.rb:14:in `run'
	/usr/src/app/lib/cc/cli/command.rb:70:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:22:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:8:in `run'
	/usr/src/app/bin/codeclimate:6:in `<main>'
```

**Comment by dblandin** [comment]
I don't think we use a `CODE_PATH` environment variable. You might be thinking of `CODECLIMATE_CODE`. Our wrapper script provides the currently supported docker invocation: https://github.com/codeclimate/codeclimate/blob/master/codeclimate-wrapper

This simplified version might work for you:

```bash
docker run
  --env CODECLIMATE_CODE=$PWD
  --env CODECLIMATE_TMP=/tmp/cc
  --volume "$PWD":/code
  --volume "/tmp/cc":/tmp/cc
  --volume /var/run/docker.sock:/var/run/docker.sock
    codeclimate/codeclimate
```

**Comment by devth** [comment]
@dblandin thanks, got it working. Not sure where I got `CODE_PATH` from; it's been a few weeks since I worked on it.

**Comment by dblandin** [comment]
Awesome 👍
